export const careers={
'Full-Stack Developer':{skills:['HTML/CSS','JavaScript','Git','React','Node.js','SQL','REST APIs','Testing'],projects:[['Expense Tracker with Auth','React','Node.js','SQL','REST APIs'],['Real-time Chat App','JavaScript','Node.js','Git'],['Portfolio with CI Tests','HTML/CSS','Testing','Git']]},
'Data Scientist':{skills:['Python','Statistics','SQL','Pandas','Data Visualization','Machine Learning'],projects:[['Campus Placement Predictor','Python','Pandas','Machine Learning'],['Sales Analytics Dashboard','SQL','Data Visualization','Pandas']]},
'AI/ML Engineer':{skills:['Python','Statistics','Machine Learning','Deep Learning','PyTorch','MLOps'],projects:[['Image Classifier API','Python','Deep Learning','PyTorch','MLOps'],['Model Comparison Study','Python','Statistics','Machine Learning']]},
'Embedded Systems Engineer':{skills:['C','Digital Electronics','Microcontrollers','Communication Protocols','RTOS','PCB Design'],projects:[['Sensor Data Logger','C','Microcontrollers','Communication Protocols'],['RTOS Motor Controller','C','RTOS','Digital Electronics']]},
'Cybersecurity Analyst':{skills:['Networking','Linux','Python','Web Security','Cryptography','Penetration Testing'],projects:[['Home Lab Vulnerability Scan','Networking','Linux','Penetration Testing'],['Password Manager','Python','Cryptography','Web Security']]},
'Mechanical Design Engineer':{skills:['Engineering Drawing','CAD','Materials','Manufacturing Processes','FEA'],projects:[['Gearbox Design in CAD','CAD','Engineering Drawing','Materials'],['Bracket Stress Analysis','CAD','FEA']]},
'Civil / Structural Engineer':{skills:['Structural Analysis','AutoCAD','BIM','Construction Management','Project Planning'],projects:[['Two-Storey Building Model','AutoCAD','BIM','Structural Analysis'],['Site Schedule Plan','Project Planning','Construction Management']]}}
export const deps={React:'JavaScript','Node.js':'JavaScript','REST APIs':'Node.js',Pandas:'Python','Machine Learning':'Statistics','Deep Learning':'Machine Learning',PyTorch:'Deep Learning',MLOps:'Machine Learning',Microcontrollers:'Digital Electronics',RTOS:'Microcontrollers','Web Security':'Networking','Penetration Testing':'Web Security',FEA:'CAD',BIM:'AutoCAD'}
export const aliases={JavaScript:['js'],'Node.js':['node','nodejs'],React:['reactjs'],SQL:['postgres','postgresql','mysql'],'Machine Learning':['ml','scikit-learn'],Git:['github'],CAD:['solidworks'],'HTML/CSS':['html','css'],'Data Visualization':['matplotlib','power bi','tableau']}
