import {useState,useEffect,useCallback} from 'react'
const api=async(p,o={})=>{const t=localStorage.getItem('t'),r=await fetch('/api'+p,{...o,headers:{'Content-Type':'application/json',...(t&&{Authorization:'Bearer '+t})},body:o.body&&JSON.stringify(o.body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
const LV=['Missing','Beginner','Comfortable','Strong'],I='w-full rounded-lg border border-line bg-paper px-3 py-2',B='rounded-lg bg-accent px-4 py-2 font-semibold text-paper disabled:opacity-50'
const C=({children,className=''})=><section className={`rounded-xl border border-line bg-card p-5 ${className}`}>{children}</section>
const H=({children})=><h2 className="mb-3 text-lg font-semibold">{children}</h2>
function Auth({onIn}){const[m,setM]=useState('login'),[f,setF]=useState({email:'',password:''}),[e,setE]=useState('')
const go=async ev=>{ev.preventDefault();try{localStorage.setItem('t',(await api('/auth/'+m,{method:'POST',body:f})).token);onIn()}catch(x){setE(x.message)}}
return<main className="mx-auto grid min-h-screen max-w-md content-center gap-4 p-6"><h1 className="text-4xl font-extrabold">EduNav AI</h1><p className="text-mute">Your career, your roadmap, your next move.</p>
<form onSubmit={go} className="grid gap-3"><input className={I} type="email" placeholder="Email" value={f.email} onChange={x=>setF({...f,email:x.target.value})} required/><input className={I} type="password" placeholder="Password (8+ characters)" value={f.password} onChange={x=>setF({...f,password:x.target.value})} required/>
{e&&<p role="alert" className="text-sm text-red-500">{e}</p>}<button className={B}>{m=='login'?'Sign in':'Create account'}</button></form>
<button className="text-sm text-accent" onClick={()=>{setM(m=='login'?'register':'login');setE('')}}>{m=='login'?'New here? Create an account':'Have an account? Sign in'}</button></main>}
const Overview=({d,reload})=>{const{profile:p,analysis:a,careers:cs}=d,n=a.roadmap[0]
return<div className="grid gap-4 md:grid-cols-3"><C><p className="text-sm text-mute">Readiness for {p.goal}</p><p className="text-7xl font-extrabold text-accent">{a.progress.pct}%</p><p className="text-sm text-mute">{a.progress.strong} of {a.progress.total} core skills at Comfortable or better</p></C>
<C className="md:col-span-2"><H>Next step</H>{n?<><p className="text-2xl font-semibold">Learn {n.skill}</p><p className="mt-1 text-mute">{n.why}</p><p className="mt-3 text-sm">About {a.progress.hoursLeft}h left, roughly {a.progress.weeks} weeks at {p.hoursPerWeek}h/week.</p></>:<p>You cover every core skill for this path. Pick a project or compare another career.</p>}</C>
<C className="md:col-span-3"><H>Compare careers</H><div className="grid gap-2">{cs.map(c=><button key={c.name} onClick={()=>api('/profile',{method:'PUT',body:{goal:c.name}}).then(reload)} className={`rounded-lg border p-3 text-left ${c.name==p.goal?'border-accent':'border-line'}`}><span className="flex justify-between"><span>{c.name}{c.name==p.goal&&' (current goal)'}</span><b>{c.pct}%</b></span><span className="mt-2 block h-2 rounded bg-line"><span className="block h-2 rounded bg-accent" style={{width:c.pct+'%'}}/></span></button>)}</div><p className="mt-2 text-sm text-mute">Select a career to make it your goal.</p></C></div>}
function Profile({d,reload}){const[p,setP]=useState({...d.profile,it:d.profile.interests.join(', '),pt:d.profile.projects.join('\n')}),[ns,setNs]=useState(''),[m,setM]=useState('')
const set=(k,v)=>setP(x=>({...x,[k]:v})),names=[...new Set([...d.catalog[p.goal],...Object.keys(p.skills)])],L=({t,children})=><label className="grid gap-1 text-sm"><span className="text-mute">{t}</span>{children}</label>
const save=async()=>{await api('/profile',{method:'PUT',body:{...p,interests:p.it.split(',').map(s=>s.trim()).filter(Boolean),projects:p.pt.split('\n').map(s=>s.trim()).filter(Boolean)}});setM('Saved');reload()}
return<div className="grid gap-4 md:grid-cols-2"><C className="grid gap-3"><H>About you</H><L t="Name"><input className={I} value={p.name} onChange={e=>set('name',e.target.value)}/></L>
<L t="Branch"><select className={I} value={p.branch} onChange={e=>set('branch',e.target.value)}>{['Computer Science & IT','Electrical & Electronics','Mechanical','Civil','Chemical','Other'].map(b=><option key={b}>{b}</option>)}</select></L>
<div className="grid grid-cols-2 gap-3"><L t="Semester"><input className={I} type="number" min="1" max="8" value={p.semester} onChange={e=>set('semester',e.target.value)}/></L><L t="Study hours per week"><input className={I} type="number" min="1" max="60" value={p.hoursPerWeek} onChange={e=>set('hoursPerWeek',e.target.value)}/></L></div>
<L t="Career goal"><select className={I} value={p.goal} onChange={e=>set('goal',e.target.value)}>{Object.keys(d.catalog).map(g=><option key={g}>{g}</option>)}</select></L>
<L t="Interests (comma separated)"><input className={I} value={p.it} onChange={e=>set('it',e.target.value)}/></L><L t="Projects done (one per line)"><textarea className={I} rows="3" value={p.pt} onChange={e=>set('pt',e.target.value)}/></L>
<div className="flex items-center gap-3"><button className={B} onClick={save}>Save profile</button><span role="status" className="text-sm text-mute">{m}</span></div></C>
<C><H>Skills for {p.goal}</H><div className="grid gap-2">{names.map(k=><div key={k} className="flex items-center justify-between gap-3"><span>{k}</span><select aria-label={k} className={I+' !w-40'} value={p.skills[k]??0} onChange={e=>set('skills',{...p.skills,[k]:+e.target.value})}>{LV.map((l,i)=><option key={l} value={i}>{l}</option>)}</select></div>)}</div>
<div className="mt-4 flex gap-2"><input className={I} placeholder="Add another skill" value={ns} onChange={e=>setNs(e.target.value)}/><button className={B} onClick={()=>{ns.trim()&&set('skills',{...p.skills,[ns.trim()]:1});setNs('')}}>Add skill</button></div></C></div>}
const Roadmap=({d,reload})=>{const a=d.analysis;return<div className="grid gap-4"><C><H>Your route to {d.profile.goal}</H>{!a.roadmap.length&&<p>Nothing left on this route. Update your goal to keep going.</p>}
<ol className="ml-3 space-y-6 border-l-2 border-accent">{a.roadmap.map(r=><li key={r.skill} className="relative ml-6"><span className="absolute -left-[33px] top-1 h-4 w-4 rounded-full border-2 border-accent bg-paper"/><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-semibold">{r.skill}</h3><span className="text-sm text-mute">{r.status=='missing'?'Missing':'Needs work'} · about {r.hours}h</span></div>
<p className="text-mute">{r.why}</p><button className="mt-2 text-sm font-semibold text-accent" onClick={()=>api('/learned',{method:'POST',body:{skill:r.skill}}).then(reload)}>Mark as learned</button></li>)}</ol></C>
<C><H>Already strong</H><p>{a.gaps.filter(g=>g.status=='strong').map(g=>g.skill).join(', ')||'Nothing yet. Rate your skills in Profile.'}</p></C></div>}
const Projects=({d})=><div className="grid gap-4 md:grid-cols-2">{d.analysis.projects.map(p=><C key={p.name}><h3 className="text-lg font-semibold">{p.name}</h3><p className="my-2 text-mute">{p.why}</p><p className="text-sm">Skills used: {p.skills.join(', ')}</p></C>)}</div>
const Weekly=({d})=>d.analysis.weekly.length?<div className="grid gap-4 md:grid-cols-3">{d.analysis.weekly.map(w=><C key={w.week}><H>Week {w.week}</H><ul className="grid gap-1">{w.tasks.map((t,i)=><li key={i} className="flex justify-between"><span>{t.skill}</span><b>{t.hours}h</b></li>)}</ul></C>)}</div>:<C>No weekly tasks. Your roadmap is complete.</C>
function Assistant(){const[m,setM]=useState([]),[t,setT]=useState(''),[b,setB]=useState(false)
const send=async()=>{if(!t.trim()||b)return;const h=[...m,{role:'user',content:t}];setM(h);setT('');setB(true);try{setM([...h,{role:'assistant',content:(await api('/chat',{method:'POST',body:{message:t,history:m}})).reply}])}catch(e){setM([...h,{role:'assistant',content:e.message}])}setB(false)}
return<C><H>Ask about careers, projects or internships</H><div aria-live="polite" className="mb-3 grid max-h-96 gap-2 overflow-auto">{!m.length&&<p className="text-mute">Try: What should I learn next? Which project should I build?</p>}{m.map((x,i)=><p key={i} className={`max-w-[85%] whitespace-pre-wrap rounded-lg p-3 ${x.role=='user'?'justify-self-end bg-accent text-paper':'bg-paper'}`}>{x.content}</p>)}{b&&<p className="text-mute">Thinking…</p>}</div>
<div className="flex gap-2"><input className={I} value={t} onChange={e=>setT(e.target.value)} onKeyDown={e=>e.key=='Enter'&&send()} placeholder="Ask EduNav"/><button className={B} onClick={send}>Send</button></div></C>}
function Resume({reload}){const[t,setT]=useState(''),[r,setR]=useState(null),[e,setE]=useState('')
const run=async apply=>{setE('');try{setR(await api('/resume',{method:'POST',body:{text:t,apply}}));apply&&reload()}catch(x){setE(x.message)}}
return<div className="grid gap-4 md:grid-cols-2"><C><H>Paste your resume text</H><textarea className={I} rows="14" value={t} onChange={x=>setT(x.target.value)}/><button className={B+' mt-3'} disabled={t.length<20} onClick={()=>run(false)}>Analyze resume</button>{e&&<p role="alert" className="mt-2 text-sm text-red-500">{e}</p>}</C>
<C><H>Results</H>{!r?<p className="text-mute">Skills found, gaps for your goal and fixes will appear here.</p>:<div className="grid gap-3"><p><b>Skills found:</b> {r.found.join(', ')||'none detected'}</p><p><b>Missing for {r.goal}:</b> {r.missing.join(', ')||'none'}</p><ul className="list-disc pl-5">{r.tips.map(x=><li key={x}>{x}</li>)}</ul><button className={B} onClick={()=>run(true)}>Add found skills to my profile</button></div>}</C></div>}
export default function App(){const[auth,setAuth]=useState(!!localStorage.getItem('t')),[d,setD]=useState(null),[tab,setTab]=useState('Overview'),[dark,setDark]=useState(localStorage.getItem('d')=='1'),[first,setFirst]=useState(true)
useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('d',dark?1:0)},[dark])
const load=useCallback(()=>api('/dashboard').then(x=>{setD(x);setFirst(f=>{f&&!x.profile.setup&&setTab('Profile');return false})}).catch(()=>{localStorage.removeItem('t');setAuth(false)}),[])
useEffect(()=>{auth&&load()},[auth,load])
if(!auth)return<Auth onIn={()=>setAuth(true)}/>
if(!d)return<p className="p-8">Loading…</p>
const V={Overview,Profile,Roadmap,Projects,Weekly,Assistant,Resume}[tab]
return<div className="mx-auto max-w-5xl p-4"><header className="mb-4 flex items-center justify-between"><h1 className="text-2xl font-extrabold">EduNav AI</h1><div className="flex gap-3 text-sm"><button onClick={()=>setDark(!dark)}>{dark?'Light mode':'Dark mode'}</button><button onClick={()=>{localStorage.removeItem('t');setAuth(false);setD(null)}}>Sign out</button></div></header>
<nav className="mb-4 flex gap-1 overflow-x-auto border-b border-line">{['Overview','Profile','Roadmap','Projects','Weekly','Assistant','Resume'].map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap px-3 py-2 ${tab==x?'border-b-2 border-accent font-semibold':'text-mute'}`}>{x}</button>)}</nav>
<main><V key={tab+d.profile.goal} d={d} reload={load}/></main></div>}
